stages:
  - buildForTest
  - test
  - build
  - review
  - staging
  - production

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

install-dependencies:
  image: cypress/base:10
  stage: buildForTest
  script:
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
      - npm ci
      - $(npm bin)/print-env CI
      - npm run cy:verify
  cache:
    paths:
      - node_modules/
  only:
    - branches

test-apps:
  image: cypress/browsers:chrome67
  stage: test
  script:
    - npm ci
    - npm run test:e2e:ci
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
  only:
    - branches

build-app:
  image: node:10.14.2
  stage: build
  variables:
    BUILD_CONFIGURATION: 'production'
  dependencies:
    - install-dependencies
  script:
    - npm run build
  artifacts:
    expire_in: 1hr
    paths:
      - public/

review:
  stage: review
  script:
    - command deploy
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
    - staging

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - command destroy
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master
    - staging

deploy-staging:
  image: node:10.14.2
  stage: deploy
  dependencies:
    - build-app
  script:
    - rsync -avuz -e 'ssh -i ~/.ssh/id_rsa' $CI_PROJECT_DIR/public/ dev@167.99.173.145:/var/www/cc
  environment:
    name: staging
    url: https://cc.it-zam.com
  only:
    - staging

deploy-production:
  image: node:10.14.2
  stage: deploy
  dependencies:
    - build-app
  script:
    - rsync -avuz -e 'ssh -i ~/.ssh/id_rsa' $CI_PROJECT_DIR/public/ dev@167.99.173.145:/var/www/cc
  environment:
    name: production
    url: https://cc.itzam.ec
  only:
    - master
