stages:
  - buildForTest
  - test
  - build-app-staging
  - build-app-production
  - review
  - staging
  - production

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

install-dependencies:
  image: cypress/base:10
  stage: buildForTest
  script:
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
      - npm ci
      - $(npm bin)/print-env CI
      - npm run cy:verify
  cache:
    paths:
      - node_modules/
  only:
    - develop

test-apps:
  image: cypress/browsers:chrome67
  stage: test
  script:
    - npm ci
    - npm run test:e2e:ci
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
  only:
    - develop

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
      --env SOURCE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
  except:
    - branches

review:
  stage: review
  script:
    - command deploy
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: stop_review
  except:
    - branches
    - master
    - staging

stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - command destroy
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  when: manual
  except:
    - branches
    - master
    - staging

build-app-staging:
  image: node:10.14.2
  stage: build-app-staging
  script:
    - npm install
    - npm run build:staging
  artifacts:
    expire_in: 1hr
    paths:
      - public/
  cache:
    paths:
      - public/
  only:
    - staging

deploy-staging:
  image: ubuntu:16.04
  stage: staging
  dependencies:
    - build-app-staging
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_STAGING" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $IP_STAGING >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    ##- apt install net-tools
    ##- ifconfig
  script:
    #- ssh dev@$IP_STAGING
    #- scp -r ~/.ssh/id_rsa public/ dev@$IP_STAGING:/var/www/cc
    ##- ssh dev@$IP_STAGING "cd /var/www/cc && git checkout master && git pull origin staging && npm install && npm run build && exit"
    #- scp -P22 -r public/ dev@$IP_STAGING:/var/www/cc/
    - rsync -rp --chmod=u+rwx,g+rwx,o+rwx public/. dev@$IP_STAGING:/var/www/cc/public/
    - ssh dev@$IP_STAGING "cd /var/www/ && chmod 545 cc/ && chmod 545 cc/public/ && exit"
  cache:
    paths:
      - public/
  environment:
    name: staging
    url: https://cc.it-zam.com
  only:
    - staging

build-app-production:
  image: node:10.14.2
  stage: build-app-production
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1hr
    paths:
      - public/
  cache:
    paths:
      - public/
  only:
    - master

deploy-production:
  image: ubuntu:16.04
  stage: production
  dependencies:
    - build-app-production
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_PRODUCTION" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $IP_PRODUCTION >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    #- ssh dev@$IP_PRODUCTION
    #- scp -r ~/.ssh/id_rsa public/ dev@$IP_PRODUCTION:/var/www/cc
    ##- ssh dev@$IP_PRODUCTION "cd /var/www/cc && git checkout master && git pull origin staging && npm install && npm run build && exit"
    #- scp -P22 -r public/ dev@$IP_PRODUCTION:/var/www/cc
    - rsync -rp --chmod=u+rwx,g+rwx,o+rwx public/. dev@$IP_PRODUCTION:/var/www/cc/public/
    - ssh dev@$IP_PRODUCTION "cd /var/www/ && chmod 545 cc/ && chmod 545 cc/public/ && exit"
  cache:
    paths:
      - public/
  environment:
    name: production
    url: https://cc.itzam.ec
  only:
    - master
